### ISSUE TITLE
[Generic UART] 323; - 723; Use UART in Generic way (On demmand)

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/AP-Sinapse#107]
[Act over UART](https://github.com/Sinapse-Energia/AP-Sinapse/wiki/MQTT-Sinapse-API#send-payload-through-uart-on-demmand)

[Response from UART](https://github.com/Sinapse-Energia/AP-Sinapse/wiki/MQTT-Sinapse-API#generic-uart-information)

**Comment by fpgamcu** [comment]
For now there is possible to use GPRS/WIFI UARTs with this command. Maybe it is good for debug. But should we have define to disable usage of in use UARTs by this command?

**Comment by GonzSanch** [comment]
About UART's response. We connect an EN to a particle sensor with UART output. The output protocol of the sensor is the following: UART; baud rate: 9600, databits: 8, stopbits: 1, parity: no.

So we send this configuration: 130;1;9600;8;1;0;

After setting the UART, the next step it's send a 'Read particle measuring' action, that  code is: 0x68 0x01 0x04 0x93. Then I send: 323;1;68010493;HEX;0;

The expected response should be: 0x40 0x05 0x04 0xDF1 0xDF2 0xDF3 0xDF4 0x(Checksum)
example: 40 05 04 00 30 00 31 56

Instead of this the response I got its: 42 40 05 04

If I send an erroneous message the response should be: 0x96 0x96

But I get:  723;700035;1;42 96 96 42 4D;HEX;-1;-1;1354628917;
or
723;700035;1;42 96 96;HEX;-1;-1;1354628917;

In other test looked like it was printing the first byte from the last message. I will attach some screenshots here. I tried to send with an USB-TTL converter different messages in HEX and ASCII.

PD: Full Datasheet of the particle sensor: https://sensing.honeywell.com/honeywell-sensing-hpm-series-particle-sensors-datasheet-32322550-c-en.pdf

I set the EN with the sensor plugged in the External 3 for debug. 

![testrail5](https://user-images.githubusercontent.com/38118990/38605690-5745bee0-3d74-11e8-8e37-1e1e0917e5bd.PNG)
![testrail1](https://user-images.githubusercontent.com/38118990/38605691-57659792-3d74-11e8-8b42-2f5e495c5d2c.PNG)
![testrail2](https://user-images.githubusercontent.com/38118990/38605692-57872f6a-3d74-11e8-90e7-7f1076e4646b.PNG)
![testrail3](https://user-images.githubusercontent.com/38118990/38605693-57aa39b0-3d74-11e8-8dd1-670dcc5eb67c.PNG)
![testrail4](https://user-images.githubusercontent.com/38118990/38605694-57cc118e-3d74-11e8-8391-461af4401769.PNG)

**Comment by ralcaide** [comment]
@fpgamcu , what is the status of this issue?. Could we have something soon?

**Comment by fpgamcu** [comment]
In 2 hours I will finish with testing and we will have the solution.

**Comment by ralcaide** [comment]
@fpgamcu , could you provide us feedback about the status, please? If you are not totally able to reproduce the problem, please tell us what do you need from our side. The fix of that is very necessary for us.

Problem: The sensor is sending several bytes but the AP is getting / returning only the first one

**Comment by fpgamcu** [comment]
With second option MQTT commands will be the same, and it will be possible to receive variable length answers, but it needs about 3 hours to implement and check it.

**Comment by ralcaide** [comment]
Ok, please go with the second option.

**Comment by fpgamcu** [comment]
With last commit should work as expected.
By the way, if there will be no answer from device we would be able to indicate this only by timestamp. payload in 723; answer will be the same as in last successfully received package. is it ok?

**Comment by ralcaide** [comment]
Yes, the payload is linked to the time-stamp, right?. It should be ok like that. We will test it asap.

**Comment by GonzSanch** [comment]
Testing the new commit, in HEX now the mqtt response print only the firsts bytes of the response.

Seems like the response still saving the last message sended and print it the first time you ask for the response, so you have to ask 2 times to get a true response.

Attached screenshots and test review:

1.  Send an erroneous payload, should get **0x9696** response Neg ACK
Instead i get only 96  (first par)
![test1](https://user-images.githubusercontent.com/38118990/38991297-78a59f0a-43dd-11e8-9cae-ded78e61cdc5.PNG)

2. Send Read measuring (68010493), should get (40 05 04 XX XX XX XX CHK), the answer is the last one received.
![test2](https://user-images.githubusercontent.com/38118990/38991391-e266bb7c-43dd-11e8-90f5-5b04f52df8f2.PNG)

3. Send again Read measuring, then i got the first par of bytes from the true response (**40** 05 04 XX XX XX XX CHK):
![test3](https://user-images.githubusercontent.com/38118990/38991483-41202f36-43de-11e8-983b-2da60da31921.PNG)


To get extra info I will test with an USB-TTL and Docklight.

**Comment by fpgamcu** [comment]
As I see - timestamp is 0 always - so you don't get response in all cases - device not answer or answer longer than GENERIC_UART_TIMEOUT time

**Comment by GonzSanch** [comment]
The response message is the payload on black screen. The 0 parameter that you saw its _LOCATE_ on publish window, sorry if this has been a bit confused. 

As u can see after ;-1;-1; (LAT & LONG) parameters it's the timestamp, different in each screenshot.

I dont know which its the value to GENERIC_UART_TIMEOUT but the reponse time of the sensor its <6000ms ...

**Comment by fpgamcu** [comment]
sorry, my fault :)
GENERIC_UART_TIMEOUT is 1000 msec, maybe better will be to increase for this kind of sensor. GENERIC_UART_TIMEOUT is defined in Definitions.h file.

**Comment by ralcaide** [comment]
Ok, we will test with this value

**Comment by GonzSanch** [comment]
Tested with an increment on GENERIC_UART_TIMEOUT (6000ms) and get the same result. 

![captura](https://user-images.githubusercontent.com/38118990/39016130-b7778440-441f-11e8-8dad-26e90329936d.PNG)

**Comment by fpgamcu** [comment]
Can you connect UART sniffer (RX and GND of USB-UART to TX and GND of sensor) to sensor in order to confirm that sensor sends more than one byte?

**Comment by ralcaide** [comment]
Tested by @GonzSanch and passed.
