### ISSUE TITLE
[CMC - Metering] To improve the metering commands of the CMC

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/AP-Sinapse#146]
Now, there are some double definitions of commands in CMC and lack of information. To do:

1. Change 1; for L3_READ_METERING_OD; . See wiki
2. Change 4; for L3_READ_METERING_P;. See wiki
3. Change 103; for L3_READ_METERING_R; See wiki
4. Add to L3_READ_METERING_R the missed fields. See wiki

**Comment by fpgamcu** [comment]
For now added missing fields with value -1 because analyzer have no such parameters (maybe I am wrong and missed something :) )

**Comment by ralcaide** [comment]
The command L3_READ_METERING_P is not working correctly. It is returning  999;1;;Unknown Message;
@fpgamcu , please take a look

**Comment by fpgamcu** [comment]
After test seems like L3_READ_METERING_P command is working, but in a wrong way:
>Published: SUPERTEST/CMC/ACT/ABCDEF : L3_READ_METERING_P;2;00:00;11:30;-1;
Received: SUPERTEST/CMC/ACT/ABCDEF : L3_READ_METERING_P;2;00:00;11:30;-1;
Received: SUPERTEST/CMC/DEBUG : Node ABCDEF <10-7-2018 03:22:51> Incoming message #SUPERTEST/CMC/ACT/ABCDEF#:#L3_READ_METERING_P;2;00:00;11:30;-1;#
Received: SUPERTEST/CMC/DEBUG : Node ABCDEF <10-7-2018 03:23:46> Sended Ping getting 1
Received: SUPERTEST/CMC/PERIODIC : 100;ABCDEF;0;0;0;0.0;220.0;0.0;0.0;0;0.0;0;0.0;0;0;
Received: SUPERTEST/CMC/DEBUG : Node ABCDEF <10-7-2018 03:24:44> Sended Ping getting 1
Received: SUPERTEST/CMC/DEBUG : Node ABCDEF <10-7-2018 03:25:37> Sended Ping getting 1
Received: SUPERTEST/CMC/PERIODIC : 100;ABCDEF;0;0;0;0.0;220.0;0.0;0.0;0;0.0;0;0.0;0;0;

Looks like it is using RF ask status instead of Analyzer ask

**Comment by fpgamcu** [comment]
After fix it using correct command
>Published: SUPERTEST/CMC/ACT/ABCDEF : L3_READ_METERING_P;2;00:00;11:30;1;
Received: SUPERTEST/CMC/ACT/ABCDEF : L3_READ_METERING_P;2;00:00;11:30;1;
Received: SUPERTEST/CMC/DEBUG : Node ABCDEF <10-7-2018 03:31:03> Incoming message #SUPERTEST/CMC/ACT/ABCDEF#:#L3_READ_METERING_P;2;00:00;11:30;1;#
Received: SUPERTEST/CMC/DEBUG : Node ABCDEF <10-7-2018 03:31:58> Sended Ping getting 1
Received: SUPERTEST/CMC/PERIODIC : L3_READ_METERING_R;ABCDEF;1684300.8;1684300.8;1684300.8;1684300.8;1684300.8;1684300.8;1684300.8;1684300.8;1684300.8;1684300.8;1684300.8;1684300.8;1684300.8;1684300.8;1684300.8;1684300.8;1684300.8;1684300.8;1684300.8;;-1;-1;1;-1;-1;1684300.8;-1;-1;1684300.8;-1;-1;1684300.8;-1;-1;1684300.8;16843009;

Also seems like if you don't have Analyzer connected it displays some junk, maybe should be fixed?

**Comment by ralcaide** [comment]
Yes, please, the values should be set to "valid" initial values. If the analyzer is not connected should return -1 in each value

**Comment by ralcaide** [comment]
Another problem have been detected in the metering command. When the value of any magnitude is negative, it is added a "-" sign also to the decimal value:

`L3_READ_METERING_R;E6F314;1800.7;651.4;0.0;1540.2;408.3;235.7;235.8;235.8;235.7;0.0;410.3;-142.-1;0.0;-103.-4;0.0;0.0;423.0;152.2;0.0;0.98;-1;-1;1;-1;-1;6.8;-1;-1;14.0;-1;-1;56.2;-1;-1;50.0;1363182420;`

Here appears the value: "-142.-1"

Please fix it

**Comment by ralcaide** [comment]
@fpgamcu , please provide feedback and estimated date

**Comment by ralcaide** [comment]
@soporteHW , how was the test result of this task?. Please provide feedback and update the labels if needed

**Comment by soporteHW** [comment]
Test performed in T623

Results obtained in attached files:
[[T623]_Step4.xlsx](https://github.com/Sinapse-Energia/AP-Sinapse/files/2266203/T623._Step4.xlsx)
[[T623]_Step5.xlsx](https://github.com/Sinapse-Energia/AP-Sinapse/files/2266204/T623._Step5.xlsx)

**Comment by ralcaide** [comment]
@soporteHW , could we close this task?
