### ISSUE TITLE
[NVM][SD] Device should keep working even when the SD fails

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/AP-Sinapse#159]
Now, if the SD fails or is not inserted the AP is not working by minimum basis, neither connected to the broker. 
The device should work by minimum basis, using only RAM & Flash, even when the SD has problems or is not inserted:

GENERAL: 
- The device should be able to connect
- The BL should be executed only after 208; because the device will be able to connected and the UPD_FW_COUNT will not be decreased
- The 314; will be available and then, the SD could be formatted

EN:
- All the API commands will be available but will work only with the RAM Memory. Like 1 EPD, no persistence 

CMC:
- All the API commands available but only with RAM
- Schedulers over relays should still work. To move relay persistence to flash (like relay status).   
- Other schedulers like periodic measurements can still stays in SD and then not work without SD. Anyway it is recommendable to save them in flash also.

**Comment by ralcaide** [comment]
@fpgamcu , very high priority for next sprint. What do you think about estimation?

Regarding NVM, I think will be a good idea to save everything related with the AP (CMC/EN) in flash and all the stuff related with EPD in SD. Like that, a normal CMC could work without SD at the 100% of its functionality. What do you think?

**Comment by ralcaide** [comment]
@fpgamcu , what is the status of this task? . We are waiting to its development

**Comment by fpgamcu** [comment]
We will push the code today evening or latest on this weekend. In any case on Monday morning you will have it.

**Comment by fpgamcu** [comment]
While implementing compatibility with previous bootloader I faced issue.
Any time device is restarted bootloader is updating UPDFW_COUNT. While doing this it rewrites whole flash sector and that will erase any data outside the shared settings. So if bootloader will not be updated (old bootloader) it will always erase relays periodic settings.
We can add into shared variables some reserved field, but in any case bootloader should be updated at all devices.

**Comment by soporteHW** [comment]
Is this issue ready for to be tested? @fpgamcu @ralcaide

**Comment by ralcaide** [comment]
Yes, it is to be tested. In fact, Gonzalo have already tested it but we,ve found a problem. It is work only with new BL (after 1.30) and not with 1.30 and previous one. Test it please with old and new BL and characterize how is really working, then we will plan some improvements

**Comment by soporteHW** [comment]
Tested using BL V1.46.0 and CL V1.46.2

[Test results - T1454](https://sinapseenergia.testrail.io/index.php?/tests/view/1454)

Performed several test in order to check basis functionality in AP device.

**- Test 1: MQTT connectivity and stability**
AP device get establishes MQTT connection and successfully subscripted to All topics.
![image](https://user-images.githubusercontent.com/28917446/51980168-8ada5b00-248f-11e9-96d5-eaafee5c63b1.png)
In every main loop, AP returns messages showing SD error(as expected)
![image](https://user-images.githubusercontent.com/28917446/51980181-92016900-248f-11e9-8e9f-4b1704612874.png)
After some time, AP stability is OK. Received Ping ACK
![image](https://user-images.githubusercontent.com/28917446/51980195-9c236780-248f-11e9-913c-bbd7b138c848.png)

**- Test 2: Retrieve FW version**
Sended "209;" to retrieve FW version.
![image](https://user-images.githubusercontent.com/28917446/51980231-b52c1880-248f-11e9-8d18-e57ad154a417.png)

**- Test 3: Set up EPD**
Two EPDs set up with ID 514853, FFFFFF 
![image](https://user-images.githubusercontent.com/28917446/51980249-c37a3480-248f-11e9-8a3c-ae092e4d1fbb.png)

**- Test 4: Discover EPD in memory**
Sended "313;" to discover the EPD stored in RAM & Flash memory
![image](https://user-images.githubusercontent.com/28917446/51980284-e3115d00-248f-11e9-909b-1662e4d62f6b.png)

**- Test 5: Reset the AP**
Sended "398;0;"
![image](https://user-images.githubusercontent.com/28917446/51980297-edcbf200-248f-11e9-971f-339d649d7fbd.png)
AP reboots as expected and establishes again the MQTT connection.
Then, when we discover the EPD in memory, the memory is empty.
![image](https://user-images.githubusercontent.com/28917446/51980305-f7edf080-248f-11e9-9b17-8a7d2efb5764.png)

**- Test 6: RF communication: Actuation over EPD**
With EPD set up, sended "3;X;". EPDs work as expected (switch ON/OFF, dimming)

**- Test 7: RF communication: metering over EPD**
Sended "1;" over EPD 514853
![image](https://user-images.githubusercontent.com/28917446/51980343-0b995700-2490-11e9-8393-2a4aa1022c44.png)
All values returned are 0. It is due a CL V1.46.2 RF NEMA improve. In this version, the communication with EVO EPD is worst.

**- Test 8: Actuation over Relay outputs(On demand)**
Sended some actuations as follow:
![image](https://user-images.githubusercontent.com/28917446/51980366-1d7afa00-2490-11e9-8b7b-5ee8eb03fa45.png)
In all cases, relays switch as expected and AP device returns "L3_READ_RELAY_STATUS_R" message with last relay status.

**- Test 9: Actuation over Relay outputs(Scheduled)**
Performed a scheduled actuation over REL1, REL2 and REL3.
![image](https://user-images.githubusercontent.com/28917446/51980382-2a97e900-2490-11e9-8661-b85d964c6562.png)
When scheduled is enable, if we send a "L3_READ_RELAY_STATUS_OD;" message, AP device shows the actual relay status after change.
Idem when scheduled is disabled.
![image](https://user-images.githubusercontent.com/28917446/51980397-34215100-2490-11e9-8d0f-f6d27d8c51b5.png)

**- Test 10: Metering over MODBUS analyzer**
Sended "L3_READ_METERING_OD;" message:
![image](https://user-images.githubusercontent.com/28917446/51980416-3f747c80-2490-11e9-92b4-c57c8356541e.png)
Metering works as expected.

**NOTE:** Periodic features are not tested.

**Comment by ralcaide** [comment]
Working with BL 1.46 or higher.
It is not working with BL 1.30. It is necessary to find a workaround maybe with limitations but that allows the device to be update with last CLs

**Comment by ralcaide** [comment]
@fpgamcu , could you please provide options we have?
